openapi: 3.0.2
info:
  title: 'Web BP:Post'
  description: API Spec for BP
  version: '1.0'
  contact:
    name: Bakaran Project
    email: bakaranproject@gmail.com
    url: bakaranproject.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: api.bakaranproject.com
  - url: http://localhost:8000/api
tags:
  - name: Post
    description: Operation about Post
components:
  parameters:
    userId:
      name: userId
      in: path
      schema:
        type: 'string'
      required: true
    hashEmail:
      name: hashEmail
      in: path
      schema:
        type: 'string'
      required: true
    expiredVerifyEmail:
      in: query
      name: expires
      schema:
        type: string
      required: true
    signatureVerifyEmail:
      in: query
      name: signature
      schema:
        type: string
      required: true
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
  schemas:
    BasicResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
      required:
        - status
        - message
paths:
  /posts:
    post:
      tags:
        - Post
      responses:
        201:
          description: success create
    get:
      tags:
        - Post
      responses:
        200:
          description: success get all posts
  /post/{postId}:
    get:
      tags:
        - Post
      responses:
        200:
          description: success get post by post i     
    put:
      tags:
        - Post
      responses:
        200:
          description: success update post
    delete:
      tags:
        - Post
      responses:
        200:
          description: success delete post
